---
title: "PurpleAir QC Report"
output:
  html_document: 
    css: report_styles.css
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)

timezone <- pat$meta$timezone

data <- pat$data
timeRange <- range(data$datetime)

startString <- strftime(timeRange[1], "%a, %b %d", tz = timezone)
endString <- strftime(timeRange[2], "%a, %b %d", tz = timezone)

has_uptime <- !all(is.na(data$uptime))
has_memory <- !all(is.na(data$memory))
has_rssi <- !all(is.na(data$rssi))
has_pa_latency <- !all(is.na(data$pa_latency))

has_humidity <- !all(is.na(data$humidity))
has_temperature <- !all(is.na(data$temperature))
has_pressure <- !all(is.na(data$pressure))

has_pm2.5_atm <- !all(is.na(data$pm2.5_atm))
has_pm2.5_atm_a <- !all(is.na(data$pm2.5_atm_a))
has_pm2.5_atm_b <- !all(is.na(data$pm2.5_atm_b))

# Define a function for no data situation
plot_no_data <- function(datetime, parameterName) {
  value <- rep(0.5, times = length(datetime))
  plot(datetime, value, col = "transparent", xlab = "", ylab = "", yaxt = "n", ylim = c(0, 1))
  usr <- par('usr')
  x = usr[1] + (usr[2] - usr[1]) / 2
  label <- sprintf("no '%s' data available", parameterName)
  text(x, 0.5, label, cex = 2, col = "black", adj = c(0.5, 0.5))
}
```

Processed on `r paste(lubridate::now(),format(lubridate::now(), "%Z"))`.

This report displays raw measurements made between `r startString` and `r endString` UTC.

----

# Sensor `r sensor_index`

## Sensor Electronics

Look for uptime restarts or long latency times. 

```{r sensor_electroncs, fig.height = 10, echo = FALSE}
layout(matrix(seq(4)))
par(mar = c(3, 4, 4, 2) + 0.1)
if ( has_uptime ) {
  plot(data$datetime, data$uptime, pch = 15, cex = 0.5, las = 1, main = "uptime", xlab = "", ylab = "days")
} else{
  plot_no_data(data$datetime, "uptime")
}

if ( has_memory ) {
  plot(data$datetime, data$memory, pch = 15, cex = 0.5, las = 1, main = "memory", xlab = "", ylab = "MB")
} else{
  plot_no_data(data$datetime, "memory")
}

if ( has_rssi ) {
  plot(data$datetime, data$rssi, pch = 15, cex = 0.5, las = 1, main = "wifi strength", xlab = "", ylab = "dB")
} else{
  plot_no_data(data$datetime, "rssi")
}

if ( has_pa_latency ) {
  plot(data$datetime, data$pa_latency, pch = 15, cex = 0.5, las = 1, main = "latency", xlab = "", ylab = "seconds")
} else{
  plot_no_data(data$datetime, "pa_latency")
}
par(mar = c(5, 4, 4, 2) + 0.1)
layout(1)
```

## Atmospheric Variables

Look for unreasonable values, outages or clues that this might be an indoor sensor.

```{r atmospheric variables, fig.height = 10, echo = FALSE}
layout(matrix(seq(3)))
par(mar = c(3, 4, 4, 2) + 0.1)
if ( has_humidity ) {
  plot(data$datetime, data$humidity, pch = 15, cex = 0.5, las = 1, main = "humidity", xlab = "", ylab = "%")
} else{
  plot_no_data(data$datetime, "humidity")
}

if ( has_temperature ) {
  plot(data$datetime, data$temperature, pch = 15, cex = 0.5, las = 1, main = "temperature", xlab = "", ylab = "°F")
} else{
  plot_no_data(data$datetime, "temperature")
}

if ( has_pressure ) {
  plot(data$datetime, data$pressure, pch = 15, cex = 0.5, las = 1, main = "pressure", xlab = "", ylab = "millibar")
} else{
  plot_no_data(data$datetime, "pressure")
}

par(mar = c(5, 4, 4, 2) + 0.1)
layout(1)
```

## PM2.5 "atm"

Look for large differences in A and B channel time series.

```{r pm25_atm, echo = FALSE}
par(mar = c(3, 4, 4, 2) + 0.1)
plot(data$datetime, data$pm2.5_atm, pch = 15, cex = 0.5, col = "transparent", las = 1, main = "pm2.5_atm", xlab = "", ylab = "PM2.5")
points(data$datetime, data$pm2.5_atm_a, pch = 15, cex = 0.5, col = adjustcolor("blue", 0.3), xlab = "")
points(data$datetime, data$pm2.5_atm_b, pch = 15, cex = 0.5, col = adjustcolor("red", 0.3), xlab = "")
par(mar = c(5, 4, 4, 2) + 0.1)
legend(
  "topright",
  legend = c("A channel", "B channel"),
  col = c("blue", "red"),
  pch = 15
)
```

## PM2.5 AB Correlation

Are the A and B channels highly correlated?

```{r pm25_correlation, echo = FALSE}
correlation <- cor(data$pm2.5_atm_a, data$pm2.5_atm_b) %>% round(3)
title <- sprintf("A/B Channel Correlation = %0.3f", correlation)
plot(data$pm2.5_atm_a, data$pm2.5_atm_b, pch = 15, cex = 0.5, las = 1, main = title, xlab = "A channel", ylab = "B channel")
```

## PM2.5 Temp Correlation

One sensor failure mode is evidenced by strong correlation between a
PM channel and temperature measurements.

```{r pm25_temp_correlation, echo = FALSE}
if ( has_temperature ) {
  correlation_a <- cor(data$pm2.5_atm_a, data$temperature) %>% round(3)
  correlation_b <- cor(data$pm2.5_atm_b, data$temperature) %>% round(3)
  title <- sprintf("A/B Correlation with temperature = %0.3f/%0.3f", correlation_a, correlation_b)
  plot(data$temperature, data$pm2.5_atm, pch = 15, cex = 0.5, col = "transparent", las = 1, main = title, xlab = "temperature", ylab = "PM2.5")
  points(data$temperature, data$pm2.5_atm_a, pch = 15, cex = 0.5, col = adjustcolor("blue", 0.3))
  points(data$temperature, data$pm2.5_atm_b, pch = 15, cex = 0.5, col = adjustcolor("red", 0.3))
  legend(
    "topright",
    legend = c("A channel", "B channel"),
    col = c("blue", "red"),
    pch = 15
  )
} else {
  plot_no_data(data$datetime, "temperature")
}
```


----
